version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  server:
    container_name: backend
    build: .
    ports:
      - 8080:8080
    environment:
      ATLAS_URI: mongodb://mongo_db:27017
      DB_NAME: LevBlockchain

    depends_on:
      - mongo_db

volumes:
  mongo_db: {} 

